import { test, expect } from '@playwright/test';
test('A explicitly reuses an Artifact in a new Run, recovers a failed selection and refreshes source/copy details', async ({ page }) => {
 await page.goto('/');
 await page.getByLabel('访问令牌').fill('browser-test-only-credential-00000000000000000000');
 await page.getByRole('button', { name: '登录', exact: true }).click();
 await page.getByLabel('输入 CSV / JSON').setInputFiles({ name: 'first.csv', mimeType: 'text/csv', buffer: Buffer.from('id,category,value\na,x,0.1\nb,x,0.2\nc,y,invalid\n') });
 await page.getByRole('button', { name: '上传输入', exact: true }).click();
 await expect(page.locator('#input-status')).toContainText('已校验');
 await page.getByRole('button', { name: '提交任务', exact: true }).click();
 await expect(page.locator('#result')).toContainText('"total": "0.3"');
 const first = await page.locator('#detail-id').textContent();
 await page.getByRole('button', { name: '关闭详情' }).click();
 await page.getByRole('button', { name: 'MCP 只读研究', exact: true }).click();
 await page.getByRole('button', { name: '登记配置', exact: true }).click();
 await page.getByLabel('配置类型').selectOption('mcp'); await page.getByLabel('配置名称').fill('reuse-mcp'); await page.getByLabel('变更说明').fill('复用组合检查');
 await page.getByRole('button', { name: '预览变更', exact: true }).click();
 await page.getByRole('button', { name: '确认发布', exact: true }).click();
 await expect(page.getByTestId('configuration-result')).toContainText('reuse-mcp@1');
 await page.getByRole('button', { name: '关闭配置', exact: true }).click();
 await page.getByLabel('研究 MCP（选择后交付报告）').selectOption('reuse-mcp@1');
 await page.locator('#runs tr').first().getByRole('button', { name: '查看详情', exact: true }).click();
 await page.route('**/v1/artifacts/*', route => route.abort());
 await page.getByRole('button', { name: '用作新任务输入 output/valid.csv', exact: true }).click();
 await expect(page.locator('#artifact-error')).not.toBeEmpty();
 await page.unroute('**/v1/artifacts/*');
 await page.getByRole('button', { name: '用作新任务输入 output/valid.csv', exact: true }).click();
 await expect(page.locator('#input-status')).toContainText(first!);
 await expect(page.locator('#input-status')).toContainText('已取消研究 MCP');
 await expect(page.locator('#mcp-revision')).toHaveValue('');
 await page.getByRole('button', { name: '提交任务', exact: true }).click();
 await expect(page.locator('#result')).toContainText('"input_count": 2');
 const second = await page.locator('#detail-id').textContent(); expect(second).not.toBe(first);
 await expect(page.locator('#input-bindings')).toContainText(first!);
 await expect(page.locator('#input-bindings')).toContainText('已核验回收');
 await page.reload(); await expect(page.locator('#input-bindings')).toContainText(first!);
 await page.locator('#input-bindings').scrollIntoViewIfNeeded();
 await page.screenshot({ path: '.scratch/v0/evidence/ticket08/reuse-desktop.png' });
 const download = page.waitForEvent('download');
 await page.getByRole('button', { name: '下载 output/valid.csv', exact: true }).click();
 expect((await download).suggestedFilename()).toBe('valid.csv');
 await page.setViewportSize({ width: 390, height: 844 });
 await page.locator('#input-bindings').scrollIntoViewIfNeeded();
 await page.screenshot({ path: '.scratch/v0/evidence/ticket08/reuse-mobile.png' });
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 const source = await page.locator('#input-bindings').textContent();
 const artifact = source!.match(/来源 Artifact ([a-f0-9-]{36})/)![1];
 const denied = await page.request.post('/v1/runs', { headers: { Authorization: 'Bearer browser-other-test-credential-000000000000000000', 'Idempotency-Key': 'denied-reuse-browser' }, data: { prompt: 'reuse', profile: 'json-lab@1', output_contract: 'data-statistics@1', inputs: [{ artifact_id: artifact, path: 'input/reuse.csv' }] } });
 expect(denied.status()).toBe(404);
});
