import { test, expect } from '@playwright/test';
test('real browser logs in, submits, refreshes persistent details and recovers from network failure', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('访问令牌').fill('browser-test-only-credential-00000000000000000000');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.locator('#identity')).toContainText('browser-maintainer');
  await page.getByRole('button', { name: '提交任务', exact: true }).click();
  await expect(page.locator('#detail')).toBeVisible();
  await expect(page.locator('#result')).toContainText('three apples');
  await expect(page.locator('#facts')).toContainText('已核验回收');
  await page.reload();
  await expect(page.locator('#result')).toContainText('three apples');
  await page.screenshot({ path: 'test-results/ticket01-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '关闭详情' }).click();
  await page.route('**/v1/runs', route => route.abort());
  await page.getByRole('button', { name: '刷新数据' }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  await page.unroute('**/v1/runs');
  await page.getByRole('button', { name: '刷新数据' }).click();
  await expect(page.getByRole('alert')).toBeHidden();
  await page.screenshot({ path: 'test-results/ticket01-workspace.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/ticket01-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '退出', exact: true }).click();
  await expect(page.locator('#login')).toBeVisible();
  expect(errors).toEqual([]);
});
